begin;
do $$
declare u uuid:=gen_random_uuid(); peer uuid:=gen_random_uuid(); t uuid:=gen_random_uuid(); a uuid; b uuid; blocked boolean; n integer;
begin
  insert into auth.users(id,email) values(u,u||'@confirmation.invalid'),(peer,peer||'@confirmation.invalid');
  insert into public.kyra_threads(id,user_id,title) values(t,u,'Fixture');
  perform set_config('role','service_role',true);
  select id into a from public.prepare_kyra_studio_confirmation(u,t,'{"selection":"one"}','one');
  select id into b from public.prepare_kyra_studio_confirmation(u,t,'{"selection":"one"}','one');
  if a is null or a<>b then raise exception 'Same pending selection was not reused'; end if;
  select id into b from public.prepare_kyra_studio_confirmation(u,t,'{"selection":"two"}','two');
  if a=b then raise exception 'Changed selection reused old confirmation'; end if;
  select count(*) into n from public.kyra_studio_confirmations where user_id=u and closed_at is null;
  if n<>1 then raise exception 'Multiple pending confirmations'; end if;
  update public.kyra_studio_confirmations set created_at=now()-interval '1 hour', expires_at=now()-interval '1 second' where id=b;
  select id into a from public.prepare_kyra_studio_confirmation(u,t,'{"selection":"two"}','two');
  if a=b then raise exception 'Expired confirmation was reused'; end if;
  blocked:=false;
  begin perform public.prepare_kyra_studio_confirmation(peer,t,'{}','peer');
  exception when others then if sqlerrm='kyra_thread_unavailable' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Peer thread confirmation accepted'; end if;
  perform set_config('role','authenticated',true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
  select count(*) into n from public.kyra_studio_confirmations;
  if n<>0 then raise exception 'Confirmation records exposed to client'; end if;
  blocked:=false;
  begin perform public.prepare_kyra_studio_confirmation(u,t,'{}','forged');
  exception when insufficient_privilege then blocked:=true; end;
  if not blocked then raise exception 'Client can forge server confirmation'; end if;
end;
$$;
rollback;
