begin;
do $$
declare u uuid:=gen_random_uuid(); g uuid:=gen_random_uuid(); p text; p2 text; o text; r jsonb; t uuid; blocked boolean;
begin
  p:='users/'||u||'/closet/'||gen_random_uuid()||'.jpg';
  p2:='users/'||u||'/closet/'||gen_random_uuid()||'.jpg';
  o:=regexp_replace(p,'\.jpg$','-cutout.png');
  insert into auth.users(id,email) values(u,u||'@cutout.invalid');
  insert into auth.users(id,is_anonymous) values(g,true);
  insert into storage.objects(bucket_id,name) values('user-content',p),('user-content',p2),('user-content',o);
  perform set_config('role','service_role',true);
  blocked:=false;
  begin perform public.claim_closet_cutout(u,p,'one');
  exception when others then if sqlerrm='cutout_disabled' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Disabled fallback reserved processing'; end if;
  update public.closet_cutout_config set enabled=true,daily_limit=1;
  blocked:=false;
  begin perform public.claim_closet_cutout(g,'users/'||g||'/closet/'||gen_random_uuid()||'.jpg','guest');
  exception when others then if sqlerrm='cutout_account_required' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Guest reserved vendor processing'; end if;
  r:=public.claim_closet_cutout(u,p,'one'); t:=(r->>'token')::uuid;
  if r->>'state'<>'reserved' then raise exception 'Initial claim failed'; end if;
  r:=public.claim_closet_cutout(u,p,'different-key');
  if r->>'state'<>'pending' then raise exception 'Same source charged twice'; end if;
  blocked:=false;
  begin perform public.claim_closet_cutout(u,p2,'one');
  exception when others then if sqlerrm='cutout_key_conflict' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Key reused for another source'; end if;
  blocked:=false;
  begin perform public.claim_closet_cutout(u,p2,'two');
  exception when others then if sqlerrm='cutout_quota_exhausted' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Quota exceeded'; end if;
  perform public.begin_closet_cutout(t);
  blocked:=false;
  begin perform public.begin_closet_cutout(t);
  exception when others then if sqlerrm='cutout_dispatch_unavailable' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Provider dispatched twice'; end if;
  blocked:=false;
  begin perform public.complete_closet_cutout(t,p2);
  exception when others then if sqlerrm='cutout_completion_unavailable' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Wrong output completed'; end if;
  perform public.complete_closet_cutout(t,o);
  perform public.fail_closet_cutout(t,true);
  r:=public.claim_closet_cutout(u,p,'one');
  if r->>'state'<>'complete' or r->>'path'<>o then raise exception 'Completion replay lost'; end if;
  update public.closet_cutout_config set daily_limit=10,monthly_limit=2;
  r:=public.claim_closet_cutout(u,p2,'failed-request'); t:=(r->>'token')::uuid;
  perform public.begin_closet_cutout(t);
  perform public.fail_closet_cutout(t,false);
  if not (select provider_attempted from public.closet_cutout_requests where id=t) then
    raise exception 'Failure erased durable dispatch marker';
  end if;
  r:=public.claim_closet_cutout(u,p2,'failed-replay');
  if r->>'state'<>'pending' then raise exception 'Failed vendor request allowed another dispatch'; end if;
  blocked:=false;
  begin perform public.claim_closet_cutout(u,'users/'||g||'/closet/'||gen_random_uuid()||'.jpg','foreign');
  exception when others then if sqlerrm='cutout_invalid_input' then blocked:=true; else raise; end if; end;
  if not blocked then raise exception 'Foreign source reserved'; end if;
  perform set_config('role','authenticated',true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','is_anonymous',false)::text,true);
  if exists(select 1 from public.closet_cutout_requests) then raise exception 'Client read service ledger'; end if;
  blocked:=false;
  begin perform public.claim_closet_cutout(u,p,'one'); exception when insufficient_privilege then blocked:=true; end;
  if not blocked then raise exception 'Client called reservation RPC'; end if;
end;
$$;
rollback;
